version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - portfolio
    depends_on: 
      - backend
    restart: always

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "mysql"       # MYSQL Database host like mysql
      DB_NAME: "portfolio_db"       # MYSQL Database Name like portfolio
      DB_USER: "portfolio"       # MYSQL Database  User like root
      DB_PASSWORD: "admin123"   # MYSQL DATABASE password  Password like root
      EMAIL_USER: ""    # WRITE YOUR GMAIL NAME 
      EMAIL_PASS: ""    # WRITE YOUR GMAIL PASSWORD GENRATED BY GOOGLE PASSWORD APP
      ADMIN_EMAIL: ""   # WRITE YOUR GMAIL NAME   
    networks:
      - portfolio
    depends_on:
      db:
        condition: service_healthy
    restart: always

  admin:
    container_name: admin
    build: ./admin
    ports:
      - "5001:80"
    environment:
      DB_HOST: "mysql"             # MYSQL DATABASE HOST LIKE (mysql)
      DB_NAME: "portfolio_db"             # MYSQL DATABASE NAME LIKE (portfolio)
      DB_USER: "portfolio"             # MYSQL DATABASE USERNAME LIKE (root)
      DB_PASSWORD: "admin123"         # MYSQL DATABASE PASSWORD LIKE (root)
      ADMIN_PASSWORD: "admin123"      # ENTER YOUR ADMIN PANNEL PASSWORD LIKE (admin123)  
    networks:
      - portfolio
    volumes:
      - ./admin:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    restart: always
  
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root" # MYSQL DATABASE PASSWORD LIKE (root) 
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - portfolio
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
      start_period: 30s

volumes:
  portfolio:

networks:
  portfolio:
    driver: bridge
