prometheus:
  service:
    type: NodePort
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - devopscloud.me
    paths:
      - /prometheus
  prometheusSpec:
    retention: 15d

grafana:
  service:
    type: NodePort
  grafana.ini:
    server:
      root_url: "%(protocol)s://devopscloud.me/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - devopscloud.me
    paths:
      - /grafana
  persistence:
    enabled: true
    size: 3Gi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

alertmanager:
  service:
    type: ClusterIP


