server:
  serviceAccount:
    create: true    
  dev:
    enabled: true
  service:
    type: ClusterIP 

injector:
  enabled: true 

ui:
  enabled: true

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
      