kind: Deployment
apiVersion: apps/v1
metadata:
  name: admin
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "k8s-role"
        vault.hashicorp.com/agent-inject-secret-env: "secret/data/creds"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "secret/data/creds" -}}
          export DB_PASSWORD="{{ .Data.data.password }}"
          export ADMIN_PASSWORD="{{ .Data.data.password }}"
          export DB_USER="{{ .Data.data.user }}"
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.root_password }}"
          {{- end }}
         
    spec:
      serviceAccountName: vault-admin
      containers:
        - name: admin
          image: dev7878/portfolio-admin:3.0.0 
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - source /vault/secrets/env && node server.js   
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - containerPort: 5001
               
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /admin
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /admin
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
