kind: Deployment
apiVersion: apps/v1
metadata:
  name: admin
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin         
    spec:
      containers:
        - name: admin
          image: dev7878/portfolio-admin:3.0.0 
          imagePullPolicy: Always
          env:
            - name: DB_HOST   # HOST 
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_NAME # DB NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME

            - name: DB_USER  # DB USER 
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: DB_USER

            - name: DB_PASSWORD # DB USER PASS
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: DB_PASSWORD

            - name: ADMIN_PASSWORD # Admin Password 
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: DB_PASSWORD
                       
          ports:
            - containerPort: 5001
               
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /admin
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /admin
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
