apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: portfolio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceName: mysql-svc
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7           
          ports:
            - containerPort: 3306
          env: 
            - name: MYSQL_ROOT_PASSWORD  # PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: MYSQL_ROOT_PASSWORD     
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: mysql-sc
        resources:
          requests:
            storage: 1Gi

