apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: portfolio
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS __MYSQL_DATABASE__;

    CREATE USER IF NOT EXISTS '__MYSQL_USER__'@'%' IDENTIFIED BY '__MYSQL_USER_PASSWORD__';
    GRANT ALL PRIVILEGES ON __MYSQL_DATABASE__.* TO '__MYSQL_USER__'@'%';
    FLUSH PRIVILEGES;

    USE __MYSQL_DATABASE__;

    CREATE TABLE IF NOT EXISTS messages (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(255) NOT NULL,
      message TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      replied_message TEXT NULL,
      date DATE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;



