apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
  namespace: portfolio
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mysql-init
          image: mysql:5.7
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."
              until mysqladmin ping -h mysql -uroot -p"$ROOT_PASSWORD" --silent; do
                sleep 3
              done

              echo "MySQL is ready."

              echo "Creating database if not exists..."
              mysql -h mysql -uroot -p"$ROOT_PASSWORD" -e "
              CREATE DATABASE IF NOT EXISTS $DB_NAME;
              CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
              GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';
              FLUSH PRIVILEGES;
              "

              echo "Creating table if not exists..."
              mysql -h mysql -uroot -p"$ROOT_PASSWORD" $DB_NAME -e "
              CREATE TABLE IF NOT EXISTS messages (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                email VARCHAR(255) NOT NULL,
                message TEXT NOT NULL,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                replied_message TEXT NULL,
                date DATE
              );
              "

              echo "Database initialization complete."

          env:
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: DB_PASSWORD
