kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: portfolio
  source:
    repoURL: https://github.com/dev9913/portfolio2.0.git
    targetRevision: main
    path: k8s
  destination:
    server:  https://kubernetes.default.svc  # Enter Your  Cluster IP .
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
