apiVersion: v1
kind: Service
metadata:
  name: argocd-server-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server-metrics
spec:
  ports:
    - name: http-metrics
      port: 8082
      targetPort: 8082
  selector:
    app.kubernetes.io/name: argocd-server
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-metrics
    app.kubernetes.io/component: application-controller
spec:
    ports:
    - name: http-metrics
      port: 8082
      targetPort: 8082
    selector:
        app.kubernetes.io/name: argocd-application-controller
