apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: argocd-notifications-secret
    creationPolicy: Owner

  data:
    - secretKey: email-username
      remoteRef:
        key: argocd/notifications
        property: email-username

    - secretKey: email-password
      remoteRef:
        key: argocd/notifications
        property: email-password
