apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: "http://<internal-VM-IP>:8080"  

  service.email: |
    username: $email-username
    password: $email-password
    host: smtp.gmail.com
    port: 465
    from: $email-username

  template.email-health-degraded: |
    email:
      subject: "[ArgoCD] {{.app.metadata.name}} health is {{.app.status.health.status}}"
    message: |
       Application: {{.app.metadata.name}}
       Namespace: {{.app.metadata.namespace}}
       Sync status: {{.app.status.sync.status}}
       Details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}

  template.email-deployed: |
    email:
      subject: "[ArgoCD] {{.app.metadata.name}} successfully deployed "
    message: |
       Application: {{.app.metadata.name}}
       Namespace: {{.app.metadata.namespace}}
       Sync status: {{.app.status.sync.status}}
       Details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}

  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [email-health-degraded]

  trigger.on-deployed: |
    - when: app.status.operationState.phase == 'Succeeded' and app.status.health.status == 'Healthy'
      send: [email-deployed]
